# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  overallPath: /home/vsts/work/1/s/work/1/AzureStaticWebArtifact/ProjectDashboardAzureGit

stages:
- stage: DOWNLOAD_BUILD_ARTIFACTS
  jobs:
  - job: DOWNLOAD_BUILD_ARTIFACTS
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "Listing current files"
            cd $Env:Agent.BuildDirectory
            cd work/1/
            mkdir AzureStaticWebArtifact
            cd AzureStaticWebArtifact
            git config --global user.email "rohitvarghese96@gmail.com"
            git config --global user.name "rohitvarghese96"
            git init
            git clone https://github.com/rohitvarghese96/ProjectDashboardAzureGit.git
            git ls-files
          errorActionPreference: 'continue'

      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'specific'
          project: '57f8459e-5e74-46ce-a70f-04ca96dc4f66'
          pipeline: '14'
          specificBuildWithTriggering: true
          buildVersionToDownload: 'latest'
          downloadType: 'single'
          artifactName: 'AzureStaticWebArtifact'
          downloadPath: '$(overallPath)'


      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            cd $(overallPath)
            gci
            git checkout origin/master
            git add --all
            git commit -m "Azure pipeline build"
            git push
          errorActionPreference: 'continue'



      

      

      
          








              
    

      
      


