# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DOWNLOAD_BUILD_ARTIFACTS
  jobs:
  - job: DOWNLOAD_BUILD_ARTIFACTS
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'specific'
          project: '57f8459e-5e74-46ce-a70f-04ca96dc4f66'
          pipeline: '14'
          specificBuildWithTriggering: true
          buildVersionToDownload: 'latest'
          downloadType: 'single'
          artifactName: 'AzureStaticWebArtifact'
          downloadPath: '$(Agent.BuildDirectory)'
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "Listing current files"
            cd $Env:Agent.BuildDirectory
            cd work/1/AzureStaticWebArtifact
            gci
            git checkout master
            git ls-files
          errorActionPreference: 'continue'

      - checkout: self

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            gci
            git checkout master
            git ls-files
          errorActionPreference: 'continue'

      
          








              
    

      
      


