# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DOWNLOAD_BUILD_ARTIFACTS
  jobs:
  - job: DOWNLOAD_BUILD_ARTIFACTS
    steps:
     - task: DownloadBuildArtifacts@0
       inputs:
         buildType: 'specific'
         project: '57f8459e-5e74-46ce-a70f-04ca96dc4f66'
         pipeline: '14'
         specificBuildWithTriggering: true
         buildVersionToDownload: 'latest'
         downloadType: 'single'
         artifactName: 'AzureStaticWebArtifact'
         downloadPath: '$(Build.SourcesDirectory)'


- stage: DEPLOY_ARTIFACTS
  jobs:
  - job: DEPLOY_ARTIFACTS
    steps:
      - script: |
          git config --global user.email "rohitvarghese96@gmail.com"
          git config --global user.name "rohitvarghese96"

          
          echo "Listing current files"
          gci
          
          git checkout master
          git ls-files






              
    

      
      


